name: shared
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  build_runner: ^2.10.4
  chewie: ^1.13.0
  cloud_firestore: ^6.1.0
  dartz: ^0.10.1
  feather_icons: ^1.2.0
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  firebase_storage: ^13.0.4
  flutter:
    sdk: flutter
  flutter_feather_icons: ^2.0.0+1
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.3.0
  get_it: ^9.1.1
  google_fonts: ^6.3.2
  image_picker: ^1.2.1
  intl: ^0.20.2
  mobx: ^2.5.0
  mobx_codegen: ^2.7.4
  permission_handler: ^12.0.1
  video_player: ^2.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
